name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --no-root

      - name: Run data pipeline
        run: |
          poetry run python src/collect_data.py
          poetry run python src/train_models.py
          poetry run python src/forecast_prices.py
          poetry run python src/clean_forecasts.py
          poetry run python utils/gcs_data.py

      - name: Configure Docker
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t europe-west1-docker.pkg.dev/cereals-price-prediction/streamlit-app-repo/streamlit-app .
          docker push europe-west1-docker.pkg.dev/cereals-price-prediction/streamlit-app-repo/streamlit-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy cereals-dashboard \
            --image europe-west1-docker.pkg.dev/cereals-price-prediction/streamlit-app-repo/streamlit-app \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated
