name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and Push Docker Image
        run: |
          docker build -t europe-west1-docker.pkg.dev/cereals-price-prediction/streamlit-app-repo/streamlit-app .
          docker push europe-west1-docker.pkg.dev/cereals-price-prediction/streamlit-app-repo/streamlit-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy cereals-dashboard \
            --image europe-west1-docker.pkg.dev/cereals-price-prediction/streamlit-app-repo/streamlit-app \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated
